Repository GNU-CapstoneDesign2/backend, pull requests merged in 2025-06, with the labels that each got.

#34 [FEAT #22] 외부 구조동물 API 동기화 구현
  build.gradle
  src/main/java/org/duckdns/petfinderapp/PetfinderappApplication.java
  src/main/java/org/duckdns/petfinderapp/domain/post/entity/Adopt.java
  src/main/java/org/duckdns/petfinderapp/domain/post/entity/Image.java
  src/main/java/org/duckdns/petfinderapp/domain/post/entity/PostCommon.java
  src/main/java/org/duckdns/petfinderapp/domain/post/enums/NeuterStatus.java
  src/main/java/org/duckdns/petfinderapp/domain/post/enums/PetType.java
  src/main/java/org/duckdns/petfinderapp/domain/post/enums/PostState.java
  src/main/java/org/duckdns/petfinderapp/domain/post/repository/AdoptRepository.java
  src/main/java/org/duckdns/petfinderapp/domain/post/repository/PostRepository.java
  src/main/java/org/duckdns/petfinderapp/domain/post/service/PostService.java
  src/main/java/org/duckdns/petfinderapp/domain/publicdata/client/PublicDataClient.java
  src/main/java/org/duckdns/petfinderapp/domain/publicdata/client/SgisClient.java
  src/main/java/org/duckdns/petfinderapp/domain/publicdata/config/PublicDataConfig.java
  src/main/java/org/duckdns/petfinderapp/domain/publicdata/config/PublicDataProperties.java
  src/main/java/org/duckdns/petfinderapp/domain/publicdata/config/SgisProperties.java
  src/main/java/org/duckdns/petfinderapp/domain/publicdata/dto/request/AdoptApiRequest.java
  src/main/java/org/duckdns/petfinderapp/domain/publicdata/dto/request/GeocodingApiRequest.java
  src/main/java/org/duckdns/petfinderapp/domain/publicdata/dto/response/AdoptApiResponse.java
  src/main/java/org/duckdns/petfinderapp/domain/publicdata/dto/response/AdoptItem.java
  src/main/java/org/duckdns/petfinderapp/domain/publicdata/dto/response/ErrorResponseWrapper.java
  src/main/java/org/duckdns/petfinderapp/domain/publicdata/dto/response/ItemWrapper.java
  src/main/java/org/duckdns/petfinderapp/domain/publicdata/dto/response/PublicDataBodyResponse.java
  src/main/java/org/duckdns/petfinderapp/domain/publicdata/dto/response/PublicDataHeaderResponse.java
  src/main/java/org/duckdns/petfinderapp/domain/publicdata/dto/response/PublicDataResponse.java
  src/main/java/org/duckdns/petfinderapp/domain/publicdata/dto/response/SgisAccessTokenResult.java
  src/main/java/org/duckdns/petfinderapp/domain/publicdata/dto/response/SgisGeocodingItem.java
  src/main/java/org/duckdns/petfinderapp/domain/publicdata/dto/response/SgisGeocodingResult.java
  src/main/java/org/duckdns/petfinderapp/domain/publicdata/dto/response/SgisResponse.java
  src/main/java/org/duckdns/petfinderapp/domain/publicdata/scheduler/PublicDataScheduler.java
  src/main/java/org/duckdns/petfinderapp/domain/publicdata/service/AdoptSyncService.java
  src/main/java/org/duckdns/petfinderapp/domain/publicdata/service/AdoptSyncServiceImpl.java
  src/main/java/org/duckdns/petfinderapp/domain/publicdata/service/SgisTokenService.java
Labels: :sparkles: feat

#36 [Fix #35]: Adopt 매핑 오류 해결
  src/main/java/org/duckdns/petfinderapp/domain/post/entity/Adopt.java
  src/main/java/org/duckdns/petfinderapp/domain/post/repository/AdoptRepository.java
  src/main/java/org/duckdns/petfinderapp/domain/post/service/PostService.java
  src/main/java/org/duckdns/petfinderapp/domain/publicdata/dto/response/AdoptItem.java
Labels: :bug: fix

#46 [FEAT #45] 사용자 게시글 목록 조회 기능 구현
  src/main/java/org/duckdns/petfinderapp/domain/map/controller/MapController.java
  src/main/java/org/duckdns/petfinderapp/domain/map/service/MapService.java
  src/main/java/org/duckdns/petfinderapp/domain/map/service/MapServiceImpl.java
  src/main/java/org/duckdns/petfinderapp/domain/post/dto/response/PostSummaryResponse.java
  src/main/java/org/duckdns/petfinderapp/domain/post/repository/PostRepository.java
  src/main/java/org/duckdns/petfinderapp/domain/post/service/PostService.java
  src/main/java/org/duckdns/petfinderapp/domain/user/controller/UserController.java
Labels: :sparkles: feat

#48 [Fix #47]: 'species' 파라미터 이름을 'petTypes' 파라미터로 변경
  src/main/java/org/duckdns/petfinderapp/domain/map/dto/item/MarkerItem.java
  src/main/java/org/duckdns/petfinderapp/domain/map/dto/request/MapMarkerRequest.java
  src/main/java/org/duckdns/petfinderapp/domain/map/dto/request/MapPostRequest.java
  src/main/java/org/duckdns/petfinderapp/domain/map/service/MapServiceImpl.java
Labels: :bug: fix

#55 [Fix #54] Adopt 이미지 저장 누락 버그 수정 및 응답 로깅 추가
  src/main/java/org/duckdns/petfinderapp/domain/post/entity/Adopt.java
  src/main/java/org/duckdns/petfinderapp/domain/publicdata/dto/response/AdoptItem.java
  src/main/java/org/duckdns/petfinderapp/domain/publicdata/service/AdoptSyncServiceImpl.java
Labels: :sparkles: feat, :bug: fix

#58 [Fix #57] 내가 작성한 게시글 가져오기 API 오류 해결
  src/main/java/org/duckdns/petfinderapp/domain/post/service/PostService.java
Labels: :bug: fix

#66 ♻️ Refactor[#65] 사용자 프로필 이름 및 이미지 추가
  src/main/java/org/duckdns/petfinderapp/domain/post/dto/response/ResCommon.java
Labels: :recycle: refactor

#71 [FEAT #69] 채팅방 생성 API 구현
  src/main/java/org/duckdns/petfinderapp/domain/chat/controller/ChatRoomController.java
  src/main/java/org/duckdns/petfinderapp/domain/chat/dto/request/ChatRoomCreateResponse.java
  src/main/java/org/duckdns/petfinderapp/domain/chat/dto/resposne/ChatRoomCreateRequest.java
  src/main/java/org/duckdns/petfinderapp/domain/chat/entity/ChatRoom.java
  src/main/java/org/duckdns/petfinderapp/domain/chat/exception/ChatRoomConflictException.java
  src/main/java/org/duckdns/petfinderapp/domain/chat/repository/ChatRoomRepository.java
  src/main/java/org/duckdns/petfinderapp/domain/chat/service/ChatRoomService.java
  src/main/java/org/duckdns/petfinderapp/global/error/exception/ConflictException.java
Labels: :sparkles: feat

#76 ♻️Refector[#73] 알림에 문자열 추가
  src/main/java/org/duckdns/petfinderapp/domain/push/controller/FcmController.java
  src/main/java/org/duckdns/petfinderapp/domain/push/dto/FcmResponseDto.java
  src/main/java/org/duckdns/petfinderapp/domain/push/dto/PushDto.java
  src/main/java/org/duckdns/petfinderapp/domain/push/entity/Push.java
  src/main/java/org/duckdns/petfinderapp/domain/push/service/FcmService.java
Labels: :recycle: refactor

#80 [Fix #79] 읽기전용 트랜잭션 추가 및 유저 비교 로직 개선
  src/main/java/org/duckdns/petfinderapp/domain/chat/service/ChatMessageServiceImpl.java
Labels: :bug: fix

#82 [Fix #79]: 이미지가 비어 있는 경우 처리
  src/main/java/org/duckdns/petfinderapp/domain/post/dto/PostInfoDto.java
Labels: :bug: fix

#84 [Feat #83] 채팅 메시지 읽음 처리 및 공유 게시글 기능 구현
  src/main/java/org/duckdns/petfinderapp/domain/chat/controller/ChatMessageController.java
  src/main/java/org/duckdns/petfinderapp/domain/chat/controller/ChatRoomController.java
  src/main/java/org/duckdns/petfinderapp/domain/chat/dto/ChatMessageDto.java
  src/main/java/org/duckdns/petfinderapp/domain/chat/dto/response/ChatRoomCreateRequest.java
  src/main/java/org/duckdns/petfinderapp/domain/chat/dto/response/ReadMessageDto.java
  src/main/java/org/duckdns/petfinderapp/domain/chat/dto/response/UnreadMessageResponse.java
  src/main/java/org/duckdns/petfinderapp/domain/chat/dto/resposne/ChatRoomCreateRequest.java
  src/main/java/org/duckdns/petfinderapp/domain/chat/entity/ChatMessage.java
  src/main/java/org/duckdns/petfinderapp/domain/chat/repository/ChatMessageRepository.java
  src/main/java/org/duckdns/petfinderapp/domain/chat/service/ChatMessageServiceImpl.java
  src/main/java/org/duckdns/petfinderapp/domain/chat/service/ChatRoomService.java
  src/main/java/org/duckdns/petfinderapp/domain/chat/service/ChatService.java
  src/main/java/org/duckdns/petfinderapp/domain/chat/service/ChatServiceImpl.java
  src/main/java/org/duckdns/petfinderapp/domain/post/exception/PostNotFoundException.java
Labels: :sparkles: feat, :bug: fix

#86 [Fix #85]: post null 처리
  src/main/java/org/duckdns/petfinderapp/domain/chat/service/ChatServiceImpl.java
Labels: :bug: fix

#91 ✨ Feat[#62]: Update JwtAuthenticationFilter to correctly validate Bea…
  src/main/java/org/duckdns/petfinderapp/global/security/JwtAuthenticationFilter.java
Labels: :sparkles: feat

#93 Fix: Update SimilarityNotifier to handle IOException and IllegalStateException
  src/main/java/org/duckdns/petfinderapp/domain/similarity/service/SimilarityNotifier.java
Labels: :bug: fix

#94 [Chore #62]: 자세한 로그 추가 및 예외 발생 시 로깅
  src/main/java/org/duckdns/petfinderapp/domain/chat/service/ChatServiceImpl.java
Labels: :sparkles: feat

#96 [Fix #62]: Fix notification message
  src/main/java/org/duckdns/petfinderapp/domain/similarity/service/SimilarityService.java
Labels: :bug: fix
